NAME_LENGTH_MAX = 100
NAME_LENGTH_MIN = 1
PASSWORD_LENGTH_MIN = 5
PASSWORD_LENGTH_MAX = 300
CITY_LENGTH_MIN = 2
CITY_LENGTH_MAX = 100
STATE_LENGTH_MIN = 2
STATE_LENGTH_MAX = 100
ZIPCODE_MIN = 10000
ZIPCODE_MAX = 99999
ZIPCODE_LENGTH = 5
BALANCE_MIN = 0
CITY_REGEX = r'^([a-zA-Z]+\s)*[a-zA-Z]+$'
NAME_LENGTH_ERROR = f"Name must be between {NAME_LENGTH_MIN} and {NAME_LENGTH_MAX} characters long"
PASSWORD_LENGTH_ERROR = f"Password must be between {PASSWORD_LENGTH_MIN} and {PASSWORD_LENGTH_MAX} characters long"
CITY_LENGTH_ERROR = f"City must be between {CITY_LENGTH_MIN} and {CITY_LENGTH_MAX} characters long"
CITY_REGEX_ERROR = f"City must contain only letters and spaces"
STATE_LENGTH_ERROR = f"State must be between {STATE_LENGTH_MIN} and {STATE_LENGTH_MAX} characters long"
STATE_ONEOF_ERROR = f"State must be a valid Indian state"
ZIPCODE_LENGTH_ERROR = f"Zipcode must be {ZIPCODE_LENGTH} digits long"
BALANCE_MIN_ERROR = f"Balance must be greater than or equal to {BALANCE_MIN}"
RESTAURANT_FIELDS = ['_id', 'name']
USER_TYPES = ['user', 'owner']
